#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
簡易 SQL dump 工具（當系統上沒有 mysqldump 可用時使用）
用法:
  python tools/database/remote_dump.py --host HOST --port PORT --user USER --password PWD --database DB --out dump.sql

會輸出 CREATE TABLE / VIEW / INSERT 資料，以及 routines 與 triggers 的 CREATE
"""
import argparse
import mysql.connector
import sys
import datetime

parser = argparse.ArgumentParser()
parser.add_argument('--host', required=True)
parser.add_argument('--port', type=int, default=3306)
parser.add_argument('--user', required=True)
parser.add_argument('--password', required=True)
parser.add_argument('--database', required=True)
parser.add_argument('--out', required=True)
args = parser.parse_args()

DB_CONFIG = dict(
    host=args.host,
    port=args.port,
    user=args.user,
    password=args.password,
    database=args.database,
    charset='utf8mb4',
    autocommit=True,
)

outf = open(args.out, 'w', encoding='utf-8')

def writeln(s=''):
    outf.write(s + '\n')

conn = mysql.connector.connect(**DB_CONFIG)
cur = conn.cursor()

writeln('-- Simple SQL dump generated by remote_dump.py')
writeln(f'-- {datetime.datetime.utcnow().isoformat()} UTC')
writeln(f'DROP DATABASE IF EXISTS `{args.database}`;')
writeln(f'CREATE DATABASE `{args.database}`;')
writeln(f'USE `{args.database}`;')

# Tables and views
cur.execute("SELECT table_name, table_type FROM information_schema.tables WHERE table_schema=%s ORDER BY table_name", (args.database,))
for table_name, table_type in cur.fetchall():
    writeln()
    writeln(f'-- {table_type} `{table_name}`')
    try:
        cur.execute(f"SHOW CREATE TABLE `{table_name}`")
        row = cur.fetchone()
        if row and len(row) >= 2:
            create_sql = row[1]
            writeln(create_sql + ';')
    except Exception as e:
        writeln(f'-- SHOW CREATE TABLE failed for {table_name}: {e}')

    # dump data for base tables
    if table_type.upper() == 'BASE TABLE':
        cur2 = conn.cursor()
        cur2.execute(f"SELECT * FROM `{table_name}`")
        cols = [d[0] for d in cur2.description]
        batch = []
        rownum = 0
        for r in cur2:
            vals = []
            for v in r:
                if v is None:
                    vals.append('NULL')
                else:
                    sval = str(v).replace('\\', '\\\\').replace("'", "\\'")
                    vals.append("'" + sval + "'")
            batch.append('(' + ','.join(vals) + ')')
            rownum += 1
            if len(batch) >= 1000:
                writeln(f'INSERT INTO `{table_name}` ({', '.join([f'`{c}`' for c in cols])}) VALUES')
                writeln(',\n'.join(batch) + ';')
                batch = []
        if batch:
            writeln(f'INSERT INTO `{table_name}` ({', '.join([f'`{c}`' for c in cols])}) VALUES')
            writeln(',\n'.join(batch) + ';')
        cur2.close()

# routines
cur.execute("SELECT routine_name, routine_type FROM information_schema.routines WHERE routine_schema=%s", (args.database,))
for name, rtype in cur.fetchall():
    try:
        cur.execute(f"SHOW CREATE {rtype} `{name}`")
        row = cur.fetchone()
        if row and len(row) >= 3:
            create_stmt = row[2]
            writeln('\n' + create_stmt + ';')
    except Exception as e:
        writeln(f'-- SHOW CREATE {rtype} failed for {name}: {e}')

# triggers
cur.execute("SELECT trigger_name FROM information_schema.triggers WHERE trigger_schema=%s", (args.database,))
for (tname,) in cur.fetchall():
    try:
        cur.execute(f"SHOW CREATE TRIGGER `{tname}`")
        row = cur.fetchone()
        if row and len(row) >= 3:
            # SHOW CREATE TRIGGER returns (Trigger, sql_mode, create_trigger)
            create_tr = row[2]
            writeln('\n' + create_tr + ';')
    except Exception as e:
        writeln(f'-- SHOW CREATE TRIGGER failed for {tname}: {e}')

cur.close()
conn.close()
outf.close()
print('dump written to', args.out)
